org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

mod_id=infuserapothcompat
mod_version=1.3.5
mod_group=com.digitalfeonix.infuserapothcompat

minecraft_version=26.1.2
neoforge_version=26.1.2.76
apothic_enchanting_version=26.1.2-2.0.0
placebo_version=26.1.2-10.0.1
jade_version=26.1.10+neoforge
jei_version=29.29.0.77
